use advent_of_code_2023::*;

utils::benches![
    (day01::part1, "puzzle"),
    (day01::part2, "puzzle"),
    (day02::part1, "puzzle"),
    (day02::part2, "puzzle"),
    (day03::part1, "puzzle"),
    (day03::part2, "puzzle"),
    (day04::part1, "puzzle"),
    (day04::part2, "puzzle"),
    (day05::part1, "puzzle"),
    (day05::part2, "puzzle"),
    (day06::part1, "puzzle"),
    (day06::part2, "puzzle"),
    (day07::part1, "puzzle"),
    (day07::part2, "puzzle"),
    (day08::part1, "puzzle"),
    (day08::part2, "puzzle"),
    (day09::part1, "puzzle"),
    (day09::part2, "puzzle"),
    (day10::part1, "puzzle"),
    (day10::part2, "puzzle"),
    (day11::part1, "puzzle"),
    (day11::part2, "puzzle"),
    (day13::part1, "puzzle"),
    (day13::part2, "puzzle"),
    (day23::part1, "puzzle"),
    (day23::part2, "puzzle"),
];
